### ISSUE TITLE
Input_number slider moving just on blocks of 30

### ISSUE THREAD

**Issue by srodighiero** [lizsugar/slider-button-card#3]
As per the title. I Have an helper "input_number" with range from 0 to 600, steps 5 (I will use it to set a timer).

When "sliding" the slider moves only on blocks of "30", correctly within the range of 0/600.

**Comment by lizsugar** [comment]
Oh!  This is behaving differently than the bug I already knew about!  I'll see what I can find, thank you for submitting this!

**Comment by lizsugar** [comment]
I've just pushed a fix, let me know how it goes for you!

**Comment by lizsugar** [comment]
Have not heard back in a week, and I can no longer replicate issue after pushing fix.

**Comment by srodighiero** [comment]
I had been very busy recently, I will have a look next week
